spring.application.name=advanced_course

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/user_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:625100}
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis
spring.cache.redis.time-to-live=600000

logging.level.org.springframework.cache=TRACE
logging.level.org.springframework.data.redis=TRACE